### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by ShaikhKabeer** [sussol/react-native-data-table#14]
Hello , 
Is there any simple example of this library? because we don't know how to implement it.

**Comment by Chris-Petty** [comment]
Hi, we haven't had a good chance to develop this this library further. I'm planning in the near future to do a rewrite to use new RN FlatList (ListView is deprecated) and make react-native-data-table not bound to using Realm as a database. There will be examples (probably a little expo one).

Duplicate of #1
