### ISSUE TITLE
Error of Loading 'realm/react-native' in DataTable.js

### ISSUE THREAD

**Issue by ShaikhKabeer** [sussol/react-native-data-table#15]
Hello ,

Please find the attached file as I am getting the error.

Here is my code

import React from 'react';
import { View, Text, ListView, div, AppState, NetInfo, 
    Image, AlertIOS ,Icon, TextInput, Metrics, 
    ActivityIndicatorIOS,StyleSheet, TouchableWithoutFeedback,
     SwitchIOS, Modal, TouchableHighlight, ScrollView, 
     TouchableOpacity,h1} from 'react-native';
import { DataTable, Cell, CheckableCell, EditableCell, 
        Header, HeaderCell, Row, Expansion, TableButton} from 'react-native-data-table';

export default class App extends React.Component{
    constructor(props){
        super(props)
        const dataObjects = [
            {title: 'First Title', description: 'First Description'},
            {title: 'Second Title', description: 'Second Description'},
            ]
        
        const rowHasChanged = (r1, r2) => r1 !== r2
        const ds = new ListView.DataSource({rowHasChanged})
        this.setState={
            dataSource:ds
        }
    }  
    renderHeader() {
        console.log("Showing")
        return (
        <Header style={{color:'#000', backgroundColor: '#cdcdcd', padding: 12, paddingLeft: 25, fontWeight: 'bold'}}>
        <HeaderCell
        key={1}
        isAscending={true}
        text={'Transaction #'}
        textStyle={{fontWeight: 'bold'}}
        />
        <HeaderCell
        key={2}
        isAscending={true}
        text={'By'}
        textStyle={{fontWeight: 'bold'}}
        />
        
        </Header>
        
        )
        }
    _renderRow (rowData) {
        return (
        <Row >
        {rowData.title}
        {rowData.description}
        </Row>
        )
        }
    
    render () {
        return (
         
        <DataTable
        dataSource={this.state.dataSource}
        renderRow={this._renderRow}
        renderHeader = {this.renderHeader}
        pageSize={5}
        style= {{backgroundColor: '#FFFFFF', height: 640, marginLeft: 55, marginRight: 55, borderRightWidth: 1, borderLeftWidth:1, borderBottomWidth: 1, borderColor:'#ccc' }}
        />
        
        )
        }
}

![table](https://user-images.githubusercontent.com/29751540/34294057-d1dc63fa-e72c-11e7-98ff-e4de6ed890ec.png)

**Comment by ShaikhKabeer** [comment]
Solved this one

**Comment by zim-lee** [comment]
I have the save problem. How did you fixed it?

**Comment by ShaikhKabeer** [comment]
Just download his recent commit. The issue is due to PropTypes.

**Comment by aniketnear** [comment]
Still facing it :(

**Comment by ShaikhKabeer** [comment]
Share your email. I'll send you the files. You just need to replace those ones.

**Comment by aniketnear** [comment]
Thanks, Shaikh

anikets43@gmail.com

**Comment by thuytony** [comment]
> Share your email. I'll send you the files. You just need to replace those ones.

sorry. can you send email for me: nguyenthuy220495@gmail.com?
Thanks you so much!

**Comment by jahnli** [comment]
sorry. can you send email for me: jahnli@163.cm ?
Thanks you so much!

**Comment by Chris-Petty** [comment]
Probable solution for others looking through here is #31

**Comment by anikets43** [comment]
"react-native-data-table": "github:anikets43/react-native-data-table#cb995d86fd133a072161aa6dde76909090e63ad2",

**Comment by Chris-Petty** [comment]
As it a hot topic in open source these days: make sure the above suggestion isn't taking your cryptocurrency wallet 😃
