### ISSUE TITLE
Table is not Scrolling

### ISSUE THREAD

**Issue by Amitshinde19** [sussol/react-native-data-table#18]
I have used table inside scrollview. My all screen is scrollable but don't know what reason table is not scrolling. As i am new in react native i don't know more about the behaviour of "ScrollView".
so please help me to resolve the issue.
**please share the code if possible**
Thank you in advance.

**Comment by Chris-Petty** [comment]
That's an issue/limitation with ScrollView and ListView in RN: https://github.com/facebook/react-native/issues/8024
