### ISSUE TITLE
FontFamily to Data Table

### ISSUE THREAD

**Issue by ShaikhKabeer** [sussol/react-native-data-table#19]
How do I apply FontFamily to texts in Table

**Comment by Chris-Petty** [comment]
Use the textStyle prop on your cells in render methods. Sorry for no example here but there is an example in this repo: https://github.com/sussol/mobile/blob/master/src/pages/RealmExplorer.js#L158

Note textStyle has to be passed into headerCells as well in the renderHeader method.
