### ISSUE TITLE
"A trailing comma is not permitted after the rest element" Babel error

### ISSUE THREAD

**Issue by sworupSussol** [sussol/react-native-data-table#30]
The newer version of Babel does not support trailing comma after code like 
```
const {
    style,
    textStyle,
    width,
    onPress,
    text,
    isSelected,
    isAscending,
    ...containerProps
  } = props;
```

Two files have this problem.
DataTable.js and HeaderCell.js

**Comment by Chris-Petty** [comment]
Given you've made 2 PRs
Fixed in #28 + #29 .

**Comment by sworupSussol** [comment]
Yes, I made the first PR in a hurry, did not realized there were more changes, so I closed it.

**Comment by sworupSussol** [comment]
Reopened the PRs
