### ISSUE TITLE
'ListView is deprecated and will be removed in a future release. '

### ISSUE THREAD

**Issue by jahnli** [sussol/react-native-data-table#33]
'ListView is Has been abolished    I would like to ask if this component is still used

Whether to follow the version update react-native-data-table

![image](https://user-images.githubusercontent.com/20943608/49210450-11bf7880-f3f8-11e8-813e-6f194bce8fb8.png)
![image](https://user-images.githubusercontent.com/20943608/49210478-23a11b80-f3f8-11e8-9ba0-0b8866bf76f6.png)

**Comment by Chris-Petty** [comment]
#11 

It's been on the backburner to rewrite this with RN's new list components.
