### ISSUE TITLE
Windows UWP support?

### ISSUE THREAD

**Issue by Falkyouall** [sussol/react-native-data-table#8]
Hey i've been trying to get the dataTable to work under react-native-windows but it fails with

`props.dataSource.getRow is not a function` 

next to it i implemented a ListView which works properly with the same dataSource & renderRow values,
so is it the Platform which breaks it, and will there be a version for windows?

**Comment by Chris-Petty** [comment]
Were you using Realm ListView?

In some parallel universe this repo would be updated to use RN Virtualised/FlatList.

Closing unless you're still wondering 9 months later.

**Comment by dmitryweiner** [comment]
You should update README, because you propose to use react-native ListView in it.
So, in fact, we need:
`import { ListView } from 'realm/react-native';`
Instead of:
`import { ListView } from 'react-native';`
